version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/getkin/kin-openapi
    versions:
    - 0.36.0
    - 0.38.0
    - 0.39.0
    - 0.43.0
    - 0.44.0
    - 0.45.0
    - 0.45.1
    - 0.47.0
    - 0.48.0
    - 0.49.0
    - 0.50.0
    - 0.52.0
    - 0.53.0
    - 0.54.0
    - 0.55.0
    - 0.60.0
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.14.2
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
  - dependency-name: github.com/hashicorp/go-getter
    versions:
    - 1.5.2
