# {{ .title }}

{{ .description }}

API version: {{ .version }}

### Overview

This server was generated by [stride](https://github.com/phogolabs/stride) project. 

### Prerequisite

You should have the following tools installed:

- [Golang](https://www.golang.org) language (at least version 1.12)

*Make sure that the environment variable `GOPATH` is set. The `GOPATH` directory
will be used as workspace directory for all GO projects.*

### Getting Started

if you host the source code on git and your project has a private dependencies
you should configure your git client to use git protocol. For instance for
GitHub the command that does that should be:

```
$ git config --global url."git@github.com:".insteadOf "https://github.com/"
```

The dependencies are managed by Golang's
[modules](https://github.com/golang/go/wiki/Modules) dependency system:

```bash
$ export GO111MODULE=on
$ export PROJECT_PKG={{ .project }}
$ cd $GOPATH/src/$PROJECT_PKG
$ go get ./...
```

### Running the tests

The packages is tested in
[BDD](https://en.wikipedia.org/wiki/Behavior-driven_development) style. For
that purpose, we are using [Ginkgo](http://onsi.github.io/ginkgo/) and
[Gomega](http://onsi.github.io/gomega/) packages.

You can install all of them by executing the following commands:

```bash
$ go get github.com/onsi/ginkgo/ginkgo
$ go get github.com/onsi/gomega
```

Then you can run all tests with the following command:

```bash
$ ginkgo -r
```

### Building the binary

```bash
$ mkdir -p build
$ go build -o ./build/{{ .command | dasherize | lowercase }} $PROJECT_PKG/cmd/{{ .command | dasherize | lowercase }}
```

### Running the server

To run the server, follow these simple steps:

```bash
# run the compiled binary
$ ./build/{{ .command | dasherize | lowercase }}
```

```bash
# another option is just to use golang command line tool
$ go run cmd/{{ .command | dasherize | lowercase }}/main.go
```
