openapi: 3.0.1
components:
  parameters:
    ArrayKind:
     name: ArrayKind
     schema:
       type: array
       items:
         type: string
    ArrayRef:
      $ref: '#/components/parameters/ArrayKind'
