openapi: 3.0.1
components:
  requestBodies:
    AccountStatus:
      $ref: '#/components/requestBodies/TransactionStatus'
    TransactionStatus:
      content:
        application/json:
          schema:
            type: string
            enum: [pending, completed]
