openapi: 3.0.1
components:
  schemas:
    Int32Kind:
      type: integer
      format: int32
    Int32Ref:
      $ref: '#/components/schemas/Int32Kind'
    Int64Kind:
      type: integer
      format: int64
    Int64Ref:
      $ref: '#/components/schemas/Int64Kind'
