openapi: 3.0.1
components:
  schemas:
    ZMap:
      type:
    Account:
      type: object
      required:
      - id
      properties:
        address:
          type: object
          properties:
             city:
               type: string
             country:
               type: string
             location:
               type: object
               properties:
                 latitude:
                   type: number
                   format: double
                 longitude:
                   type: number
                   format: double
             street:
               type: string
        age:
          type: integer
          format: int32
        first_name:
          type: string
        id:
          type: string
          format: uuid
          example: "5995d6a2-01b3-423c-a173-5481df49bdaf"
        last_name:
          type: string
        status:
          type: string
          enum: [pending, completed]
    AccountRef:
      $ref: '#/components/schemas/Account'
