openapi: 3.0.1
components:
  requestBodies:
    Int32Kind:
      content:
        application/json:
          schema:
            type: integer
            format: int32
    Int32Ref:
      $ref: '#/components/requestBodies/Int32Kind'
    Int64Kind:
      content:
        application/json:
          schema:
            type: integer
            format: int64
    Int64Ref:
      $ref: '#/components/requestBodies/Int64Kind'
