openapi: 3.0.1
components:
  requestBodies:
    DoubleKind:
      content:
        application/json:
          schema:
            type: number
            format: double
    DoubleRef:
      $ref: '#/components/requestBodies/DoubleKind'
    FloatKind:
      content:
        application/json:
          schema:
            type: number
            format: float
    FloatRef:
      $ref: '#/components/requestBodies/FloatKind'
