openapi: 3.0.1
servers: []
info:
  description: |
    This is a sample HTTP API. The purpose of the project is to demonstrate
    best practices for designing a good architecture for HTTP Restful server in
    Golag.  
  version: "1.0.0"
  title: Bank API 12s2aaaa s123111333
  termsOfService: https://wwww.phogolabs.com
  contact:
    email: contact@phogolabs.com
    url: https://wwww.phogolabs.com
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
components:
  schemas:
    TransactionArray:
      type: array
      items:
        $ref: '#/components/schemas/Transaction'
      xml:
        name: TransactionArray
    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
        amount:
          $ref: '#/components/schemas/Balance'
        description:
          type: string
          example: "Salmon sandwich"
        category:
          type: string
          example: "eating_out"
        merchant:
          type: string
          example: "merch_00008zIcpbAKe8shBxXUtl"
        status:
          type: string
          enum: ["pending", "completed"]
          default: "pending"
        created_at:
          type: string
          format: date-time
          example: "2015-08-22T12:20:18Z"
      xml:
        name: Transaction
    Balance:
      type: object
      properties:
        amount:
          type: integer
          format: double
          example: 10.99
        currency:
          type: string
          example: "GBP"
