name: pipeline
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up golang
        uses: actions/setup-go@v1
      - name: Run tests
        run: go test ./...
        env:
          GO111MODULE: on
